version: '3.4'

services:
  ef-interceptor-db:
    container_name: ef-interceptor-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=ef-interceptor-db
